# Generated by Django 2.1.4 on 2019-09-07 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LiuYan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('say', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=20)),
                ('PassWord', models.CharField(max_length=20)),
                ('Sex', models.CharField(max_length=5)),
                ('Age', models.IntegerField(default=18)),
                ('Number', models.IntegerField(default=110)),
                ('Content', models.CharField(max_length=100)),
            ],
        ),
    ]
